#!/bin/bash
set -e

echo "📊 Kiro Users Report — One-Click Deploy"
echo "================================"

# ── Prerequisites ──
command -v terraform >/dev/null 2>&1 || { echo "❌ Terraform is required. Install: https://www.terraform.io/downloads"; exit 1; }
command -v aws >/dev/null 2>&1 || { echo "❌ AWS CLI is required. Install: https://aws.amazon.com/cli/"; exit 1; }

# ── Step 1: Terraform setup ──
echo ""
echo "📝 Step 1: Terraform configuration"

if [ ! -f "terraform/terraform.tfvars" ]; then
    echo "Creating terraform.tfvars from example..."
    cp terraform/terraform.tfvars.example terraform/terraform.tfvars
    echo ""
    echo "⚠️  Please edit terraform/terraform.tfvars with your values:"
    echo "   - aws_account_id"
    echo "   - s3_bucket_name"
    echo "   - glue_database_name"
    echo "   - identity_store_id (required, for username lookup)"
    echo ""
    read -p "Press Enter when ready to continue..."
fi

# ── Step 2: Terraform init + apply ──
echo ""
echo "🔧 Step 2: Deploying infrastructure"

terraform -chdir=terraform init
terraform -chdir=terraform plan

read -p "Apply this plan? (yes/no): " confirm
if [ "$confirm" != "yes" ]; then
    echo "Cancelled."
    exit 0
fi

terraform -chdir=terraform apply -auto-approve

# ── Step 3: Extract outputs → app/.env ──
echo ""
echo "⚙️  Step 3: Configuring application"

AWS_REGION=$(terraform -chdir=terraform output -raw aws_region)
DATABASE_NAME=$(terraform -chdir=terraform output -raw glue_database_name)
ATHENA_OUTPUT=$(terraform -chdir=terraform output -raw athena_output_location)
IDENTITY_STORE_ID=$(terraform -chdir=terraform output -raw identity_store_id)

cat > app/.env << EOF
# Generated by deploy.sh on $(date)
AWS_REGION=${AWS_REGION}
ATHENA_DATABASE=${DATABASE_NAME}
ATHENA_OUTPUT_BUCKET=${ATHENA_OUTPUT}
IDENTITY_STORE_ID=${IDENTITY_STORE_ID}
EOF

# Add CUR config if enabled
CUR_ENABLED=$(terraform -chdir=terraform output -raw cur_enabled 2>/dev/null || echo "false")
if [ "$CUR_ENABLED" = "true" ]; then
    CUR_DATABASE=$(terraform -chdir=terraform output -raw cur_glue_database_name)
    cat >> app/.env << EOF
CUR_DATABASE=${CUR_DATABASE}
CUR_ENABLED=true
EOF
    echo "✅ CUR integration enabled"
fi

echo "✅ Created app/.env"
cat app/.env

# ── Step 4: Run Glue crawler ──
echo ""
echo "🕷️  Step 4: Running Glue crawler"

CRAWLER_NAME=$(terraform -chdir=terraform output -raw glue_crawler_name)
aws glue start-crawler --name "${CRAWLER_NAME}" --region "${AWS_REGION}"

echo "Waiting for crawler to finish (may take a few minutes)..."
while true; do
    STATUS=$(aws glue get-crawler --name "${CRAWLER_NAME}" --region "${AWS_REGION}" --query 'Crawler.State' --output text)
    if [ "$STATUS" = "READY" ]; then break; fi
    echo "  Crawler status: $STATUS"
    sleep 10
done
echo "✅ Crawler completed"

# Run CUR crawler if enabled
if [ "$CUR_ENABLED" = "true" ]; then
    echo ""
    echo "🕷️  Running CUR Glue crawler..."
    CUR_CRAWLER_NAME="${CRAWLER_NAME%-crawler}-cur-crawler"
    aws glue start-crawler --name "${CUR_CRAWLER_NAME}" --region "${AWS_REGION}" 2>/dev/null || true
    while true; do
        CUR_STATUS=$(aws glue get-crawler --name "${CUR_CRAWLER_NAME}" --region "${AWS_REGION}" --query 'Crawler.State' --output text 2>/dev/null || echo "READY")
        if [ "$CUR_STATUS" = "READY" ]; then break; fi
        echo "  CUR crawler status: $CUR_STATUS"
        sleep 10
    done
    echo "✅ CUR crawler completed"
fi

# ── Step 5: Launch dashboard ──
echo ""
echo "🚀 Step 5: Launching dashboard"
echo ""
echo "Run the following command to start the dashboard:"
echo ""
echo "cd app && python -m venv venv && source venv/bin/activate && pip install -r requirements.txt && streamlit run app.py"
echo ""
echo "✅ Deploy complete!"
